services:
  nginx:
    build:
      context: "./nginx/"
      dockerfile: "Dockerfile"
    container_name: "nginx"
    image: "custom_nginx"
    ports:
      - "8080:80"
    restart: "always"
    volumes:
      - wordpress-data:/mnt/wordpress
  
  php-wp:
    build:
      context: "./php_wp/"
      dockerfile: "Dockerfile"
    container_name: "php-wp"
    image: "custom_phpwp"
    restart: "always"
    volumes:
      - wordpress-data:/mnt/wordpress
  
  mariaDB:
    build:
      context: "./mariaDB/"
      dockerfile: "Dockerfile"
    container_name: "mariadb"
    image: "custom_maria"
    restart: "always"
    volumes:
      - db-data:/mnt/db

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/miniflint/Documents/ft_inception/srcs/db/wordpress
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/miniflint/Documents/ft_inception/srcs/db/maria
