# MariaDB container
FROM debian:bullseye

# Update and install MariaDB
RUN apt update -y && apt upgrade -y && \
    apt install -y mariadb-server gettext-base && \
    rm -rf /var/lib/apt/lists/*

# Copy the initialization script
COPY ./conf/50-init.sql /docker-entrypoint-initdb.d/50-init.sql
# Copy custom server conf
COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf


# Copy and apply the custom entrypoint script
COPY ./tools/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Expose MariaDB port
EXPOSE 3306

# Run the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]
